#spring.application.name=FinalProject
# 端口
server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 20MB # 单个文件的最大大小
      max-request-size: 50MB # 整个multipart/form-data请求的最大大小
  datasource:
    url: jdbc:mysql://localhost:3306/javaproject?useSSL=false&serverTimezone=UTC
    username: root
    password: Zhmmysql:2024
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Hibernate 设置，控制 JPA 的行为
    jpa:
      hibernate:
        ddl-auto: update  # 可以选择 update、create-drop、none 等
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # 数据源连接池配置
    hikari:
      maximum-pool-size: 10  # 最大连接池大小，视项目需求调整
      minimum-idle: 5  # 最小空闲连接数
      idle-timeout: 30000  # 空闲连接的最大存活时间
      max-lifetime: 600000  # 连接的最大生命周期
  web:
    resources:
      static-locations:
        - "classpath:/static/"
        - "file:/home/ecs-user/image/"
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

upload:
  path: /home/ecs-user/image/