#spring.application.name=FinalProject
# 端口
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javaProject?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Hibernate 设置，控制 JPA 的行为
    jpa:
      hibernate:
        ddl-auto: update  # 可以选择 update、create-drop、none 等
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # 数据源连接池配置
    hikari:
      maximum-pool-size: 10  # 最大连接池大小，视项目需求调整
      minimum-idle: 5  # 最小空闲连接数
      idle-timeout: 30000  # 空闲连接的最大存活时间
      max-lifetime: 600000  # 连接的最大生命周期
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE