#spring.application.name=FinalProject
# 端口
server:
  port: 8080

springdoc:
  api-docs:
    enabled: true # 开启OpenApi接口
    path: /v3/api-docs  # 自定义路径，默认为 "/v3/api-docs"
  swagger-ui:
    enabled: true # 开启swagger界面，依赖OpenApi，需要OpenApi同时开启
    path: /swagger-ui/index.html # 自定义路径，默认为"/swagger-ui/index.html"

#服务器部署环境
#api:
#  base-url: "http://47.97.59.189:8080"
#trusted:
#  ip: "47.97.59.189"

#本地测试环境
api:
  base-url: "http://127.0.0.1:8080"
trusted:
  ip: "localhost, 0:0:0:0:0:0:0:1, 127.0.0.1"

spring:
  servlet:
    multipart:
      max-file-size: 20MB # 单个文件的最大大小
      max-request-size: 50MB # 整个multipart/form-data请求的最大大小
  datasource:
    url: jdbc:mysql://localhost:3306/javaproject?useSSL=false&serverTimezone=UTC
    #url: jdbc:mysql://47.97.59.189:3306/javaproject?useSSL=false&serverTimezone=UTC
    username: root
    password: Zhmmysql:2024
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/javaProject?useSSL=false&serverTimezone=UTC
#    username: root
#    password: xwh123456
#    driver-class-name: com.mysql.cj.jdbc.Driver

    # Hibernate 设置，控制 JPA 的行为
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect  # 适用于 MySQL 8
      hibernate:
        ddl-auto: update  # 可以选择 update、create-drop、none 等
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # 数据源连接池配置
    hikari:
      maximum-pool-size: 10  # 最大连接池大小，视项目需求调整
      minimum-idle: 5  # 最小空闲连接数
      idle-timeout: 30000  # 空闲连接的最大存活时间
      max-lifetime: 600000  # 连接的最大生命周期
  web:
    resources:
      static-locations:
        - "classpath:/static/"
        - "file:/home/ecs-user/image/"

  mail:
    host: smtp.qq.com               # QQ 邮箱的 SMTP 服务器地址
    port: 587                       # SMTP 端口号
    username: 1473030672@qq.com  # 你的 QQ 邮箱地址
    password: pxdzrvnwxffdbafa  # 生成的授权码
    protocol: smtp                  # 协议
    properties:
      mail:
        smtp:
          auth: true                # 启用认证
          starttls:
            enable: true            # 启用 STARTTLS 加密
    default-encoding: UTF-8         # 默认编码

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#upload:
#  path: /home/ecs-user/image/

upload:
  path: ../uploads

jwt:
  secret: secureKey123
